server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    # 配置SpringCloud Gateway网关
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      # routes的参数内容是数组
      routes:
        - id: payment_route # 路由的唯一id，建议配合服务名
          # uri: http://localhost:8001 # 匹配路由名
          uri: lb://cloud-payment-service # 从注册中心获取真实调用地址实现负载均衡
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由, **通配{id}

        - id: payment_route2
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            # - Method=GET
            # - Query=param, \d+ #要有参数名param,并且值为正数才会跳转路由
            # - Host=**.atguigu.con
            # - Between=2020-03-06T12:08:15.582+08:00[Asia/Shanghai],2020-03-06T12:08:15.582+08:00[Asia/Shanghai]
            # - Before=2020-03-06T12:08:15.582+08:00[Asia/Shanghai]
        - id: temp_route
          uri: http://www.baidu.com
          predicates:
            - Path=/payment/temp/**
            # - After=2020-03-01T12:08:15.582+08:00[Asia/Shanghai]
            # - Cookie=username,zhangsan
            - Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性，并且值为正数

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true
    fetch-registry: true
    service-url:
      # 单机版
      defaultZone: http://localhost:7001/eureka
      # 集群版
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

