# 微服务端口号
server:
  port: 801

spring:
  application:
    # 服务别名---注册zookeeper到注册中心的名称
    name: cloud-consumer-zkorder
  cloud:
    zookeeper:
      # 默认localhost:2181
      connect-string: 127.0.0.1:2181