# 微服务端口
server:
  port: 7001

# 配置eureka
eureka:
  instance:
    # 主机域名
    hostname: eureka7001.com
  client:
    # 设置服务中心不将自己注册进去
    register-with-eureka: false
    # 服务中心不需要检索
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址
      # 单机版
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群版：在使用Eureka集群时此处写别的所有注册中心的服务地址
      defaultZone: http://eureka7002.com:7002/eureka/
